### ISSUE TITLE
How to install homebrew in offline mode

### ISSUE THREAD

**Issue by tanguien** [tanguien/tanguien#4]
Hello, Team.
Please help me how to install homebrew in offline mode. thanks in advance.

**Comment by groupofstars** [comment]
1. Download homebrew repository
      git clone https://github.com/Homebrew/brew.git  
2. Transfer this Homebrew folder(repository) to "/usr/local/Homebrew"
3. And create alias for "usr/local/Homebrew/bin/brew" as "brew" (shortcut on windows) and move to "usr/local/bin"
4. Set Environment Variables 
   export PATH="/usr/local/bin:$PATH"  
   export PATH="/usr/local/Homebrew/bin:$PATH"
    Execute this on terminal.

**Comment by tanguien** [comment]
It worked. Thank you @groupofstars
